{
 "title": "Metadata",
 "description": "Golang Application Runtime metrics",
 "tags": [
  "go",
  "golang"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "network",
    "label": "Network",
    "query": {
     "query": "label_values(metadata_counter, network)"
    }
   },
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "stack",
    "label": "Stack",
    "query": {
     "query": "query_result(count(container_last_seen{container_label_com_docker_stack_namespace =~\"metadata.*\"}) by (container_label_com_docker_stack_namespace))"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(go_goroutines, kubernetes_namespace)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(go_goroutines{kubernetes_namespace=\"$namespace\"}, kubernetes_pod_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Metadata Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "New contract metadata",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum without(instance) (metadata_new{job=\"$stack\",network=\"$network\",type=\"contract\"})"
    }
   ]
  },
  {
   "title": "Applied contract metadata",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum without(instance)(metadata_counter{job=\"$stack\",network=\"$network\",type=\"contract\",status=\"applied\"})"
    }
   ]
  },
  {
   "title": "Failed contract metadata",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum without(instance)(metadata_counter{job=\"$stack\",network=\"$network\",type=\"contract\", status=\"failed\"})"
    }
   ]
  },
  {
   "title": "Contract Matadata's speed resolving (item per second)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum by (status) (rate(metadata_counter{job=\"$stack\", network=\"$network\", type=\"contract\"}[$interval]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "New Token Metadata",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum without(instance) (metadata_new {job=\"$stack\", network=\"$network\", type=\"token\"})"
    }
   ]
  },
  {
   "title": "Applied Token Metadata",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum without(instance)(metadata_counter{job=\"$stack\", network=\"$network\", type=\"token\", status=\"applied\"})",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "Failed Token Metadata",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum without(instance)(metadata_counter{job=\"$stack\", network=\"$network\", type=\"token\", status=\"failed\"})"
    }
   ]
  },
  {
   "title": "Token Matadata's speed resolving (item per second)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum by(status) (rate(metadata_counter{job=\"$stack\",network=\"$network\", type=\"token\"}[$interval]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Fetching errors",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(type) (metadata_http_errors{network=\"$network\", job=\"$stack\"})",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Fetching Errors Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "sum by(type) (rate(metadata_http_errors{job=\"$stack\",network=\"$network\"}[$interval]))",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "IPFS download speed in Bytes/ms (quantile 0.75)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.75, sum by (node, le) (rate(metadata_ipfs_response_time_bucket{job=\"$stack\"}[$interval])))",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "IPFS download speed in Bytes/ms (quantile 0.9)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum by (node, le) (rate(metadata_ipfs_response_time_bucket{job=\"$stack\"}[$interval])))",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Distribution of average download speed from IPFS",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg by (le) (metadata_ipfs_response_time_bucket{job=\"$stack\"})",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Token Metadata By Mime Type (series)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "sum by(mime) (irate(metadata_mime_type{network=\"$network\",job=\"$stack\"}[$interval]))*60",
     "legendFormat": "{{ mime }}"
    }
   ]
  },
  {
   "title": "Token Metadata By Mime Type",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(mime) (rate(metadata_mime_type{network=\"$network\", job=\"$stack\"}[$interval]))",
     "legendFormat": "{{ mime }}"
    }
   ]
  },
  { "title": "Go Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "Memory in Off-Heap",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_mspan_inuse_bytes{kubernetes_namespace=\"$namespace\", kubernetes_pod_name=~\"$pod\", job=\"$stack\"}",
     "legendFormat": "mspan_inuse_bytes {{instance }}"
    },
    {
     "expr": "go_memstats_mspan_sys_bytes{kubernetes_namespace=\"$namespace\", kubernetes_pod_name=~\"$pod\", job=\"$stack\"}",
     "legendFormat": "mspan_sys_bytes {{instance }}"
    },
    {
     "expr": "go_memstats_mcache_inuse_bytes{kubernetes_namespace=\"$namespace\", kubernetes_pod_name=~\"$pod\", job=\"$stack\"}",
     "legendFormat": "mcache_inuse_bytes {{instance }}"
    },
    {
     "expr": "go_memstats_mcache_sys_bytes{kubernetes_namespace=\"$namespace\", kubernetes_pod_name=~\"$pod\", job=\"$stack\"}",
     "legendFormat": "mcache_sys_bytes {{instance }}"
    },
    {
     "expr": "go_memstats_buck_hash_sys_bytes {kubernetes_namespace=\"$namespace\", kubernetes_pod_name=~\"$pod\", job=\"$stack\"}",
     "legendFormat": "buck_hash_sys_bytes {{instance }}"
    },
    {
     "expr": "go_memstats_gc_sys_bytes{kubernetes_namespace=\"$namespace\", kubernetes_pod_name=~\"$pod\", job=\"$stack\"}",
     "legendFormat": "gc_sys_bytes {{ instance }}"
    },
    {
     "expr": "go_memstats_next_gc_bytes{kubernetes_namespace=\"$namespace\", kubernetes_pod_name=~\"$pod\", job=\"$stack\"}",
     "legendFormat": "next_gc_bytes {{instance }}"
    }
   ]
  },
  {
   "title": "Memory in Heap",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{kubernetes_namespace=\"$namespace\", kubernetes_pod_name=~\"$pod\", job=\"$stack\"}"
    },
    {
     "expr": "go_memstats_heap_sys_bytes{kubernetes_namespace=\"$namespace\", kubernetes_pod_name=~\"$pod\", job=\"$stack\"}"
    },
    {
     "expr": "go_memstats_heap_idle_bytes{kubernetes_namespace=\"$namespace\", kubernetes_pod_name=~\"$pod\", job=\"$stack\"}"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{kubernetes_namespace=\"$namespace\", kubernetes_pod_name=~\"$pod\", job=\"$stack\"}"
    },
    {
     "expr": "go_memstats_heap_released_bytes{kubernetes_namespace=\"$namespace\", kubernetes_pod_name=~\"$pod\", job=\"$stack\"}"
    }
   ]
  },
  {
   "title": "Memory in Stack",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_stack_inuse_bytes{kubernetes_namespace=\"$namespace\", kubernetes_pod_name=~\"$pod\", job=\"$stack\"}"
    },
    {
     "expr": "go_memstats_stack_sys_bytes{kubernetes_namespace=\"$namespace\", kubernetes_pod_name=~\"$pod\", job=\"$stack\"}"
    }
   ]
  },
  {
   "title": "Total Used Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_sys_bytes{kubernetes_namespace=\"$namespace\", kubernetes_pod_name=~\"$pod\", job=\"$stack\"}"
    }
   ]
  },
  {
   "title": "Number of Live Objects",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_memstats_mallocs_total{kubernetes_namespace=\"$namespace\", kubernetes_pod_name=~\"$pod\", job=\"$stack\"} - go_memstats_frees_total{kubernetes_namespace=\"$namespace\", kubernetes_pod_name=~\"$pod\", job=\"$stack\"}"
    }
   ]
  },
  {
   "title": "Rate of Objects Allocated",
   "type": "graph",
   "description": "shows how many heap objects are allocated. This is a counter value so you can use rate() to objects allocated/s.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(go_memstats_mallocs_total{kubernetes_namespace=\"$namespace\", kubernetes_pod_name=~\"$pod\", job=\"$stack\"}[$interval])"
    }
   ]
  },
  {
   "title": "Rate of a Pointer Dereferences",
   "type": "graph",
   "description": "go_memstats_lookups_total – counts how many pointer dereferences happened. This is a counter value so you can use rate() to lookups/s.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(go_memstats_lookups_total{kubernetes_namespace=\"$namespace\", kubernetes_pod_name=~\"$pod\", job=\"$stack\"}[$interval])"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 74 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{kubernetes_namespace=\"$namespace\", kubernetes_pod_name=~\"$pod\", job=\"$stack\"}"
    }
   ]
  },
  {
   "title": "Rates of Allocation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 82 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(go_memstats_alloc_bytes_total{kubernetes_namespace=\"$namespace\", kubernetes_pod_name=~\"$pod\", job=\"$stack\"}[$interval])"
    }
   ]
  },
  {
   "title": "GC duration quantile",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 82 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "go_gc_duration_seconds{kubernetes_namespace=\"$namespace\", kubernetes_pod_name=~\"$pod\", job=\"$stack\"}"
    }
   ]
  }
 ]
}